lang: en
title: jainism-beliefs
description: A curated non-exhaustive repository of references encompassing core beliefs, cosmology, scriptures, history, biographies, narratives, arts, pigrimage sites, rituals, and more.

alternates:
  - lang: en
    title: jainism-beliefs
    description: A curated non-exhaustive repository of references encompassing core beliefs, cosmology, scriptures, history, biographies, narratives, arts, pigrimage sites, rituals, and more.
  - lang: fr
    title: jainisme-croyances
    description: Un référentiel non-exhaustif et organisé de références englobant les croyances fondamentales, la cosmologie, les écritures, l'histoire, les biographies, les récits, les arts, les sites de pèlerinage, les rituels et plus encore.
